version: 3.0.{build}
image: Visual Studio 2017
environment:
  matrix:
  - SERVICESTACK_LICENSE:
      secure: 5zYTw+1lLlf6ydh05spg4huc/S2VUb+Ka5b3etCB8bvVQTAlMabBx7mcTxadOnCJo4EwPPc94TyDFEhJ031XcSds4I6NL3TEVzcY1y73tibAYaejOgWs5kNzcIjLbemn/SqHw7bvrmUSJVs2M9UFYkqyv/GaDO7O/j/VrZSZOB6KwW4QHanV7RDZpSnepoQ5fPXatIbimF3KXGTQGMHcffTBjpBsvfzOOc05fXtuvfLlv8eG3fqOvN7IUlyC9EOCBgDr6JjJFKmm9CbPNChkaLnyieMvWf2GRUSZaOjV2MmBvdSmDsIrNW26rUS+K4V5+NQ2gGWkxJApOMsg6+QvVf7UGR4npVkgkelYSW1QMVfTWxNCbLd4bEi8PRkCgxLSM07VWvNrFBPUZWkEQtNCaBHhhvbtsBOKr0CpEPJKFO4L+p7AG6wDhPED7vk3g81p
    buildconfig: Release
    buildfrx: net472
  - SERVICESTACK_LICENSE:
      secure: 5zYTw+1lLlf6ydh05spg4huc/S2VUb+Ka5b3etCB8bvVQTAlMabBx7mcTxadOnCJo4EwPPc94TyDFEhJ031XcSds4I6NL3TEVzcY1y73tibAYaejOgWs5kNzcIjLbemn/SqHw7bvrmUSJVs2M9UFYkqyv/GaDO7O/j/VrZSZOB6KwW4QHanV7RDZpSnepoQ5fPXatIbimF3KXGTQGMHcffTBjpBsvfzOOc05fXtuvfLlv8eG3fqOvN7IUlyC9EOCBgDr6JjJFKmm9CbPNChkaLnyieMvWf2GRUSZaOjV2MmBvdSmDsIrNW26rUS+K4V5+NQ2gGWkxJApOMsg6+QvVf7UGR4npVkgkelYSW1QMVfTWxNCbLd4bEi8PRkCgxLSM07VWvNrFBPUZWkEQtNCaBHhhvbtsBOKr0CpEPJKFO4L+p7AG6wDhPED7vk3g81p
    buildconfig: ReleaseNoTestDeploy
    buildfrx: net472
build_script:
- cmd: >-
    cd src
    
    cd .nuget
    
    appveyor-retry nuget.exe restore ..\ServiceStack.Webhooks.sln -DisableParallelProcessing
    
    cd ..
    
    msbuild.exe ServiceStack.Webhooks.sln /t:Rebuild /p:Configuration=%buildconfig% /verbosity:minimal
    
    cd..
test_script:
- cmd: >-
    nunit3-console "C:\projects\servicestack-webhooks\src\Webhooks.Interfaces.UnitTests\bin\%buildconfig%\%buildfrx%\ServiceStack.Webhooks.Interfaces.UnitTests.dll" "C:\projects\servicestack-webhooks\src\Webhooks.Relays.UnitTests\bin\%buildconfig%\%buildfrx%\ServiceStack.Webhooks.Relays.UnitTests.dll" "C:\projects\servicestack-webhooks\src\Webhooks.Subscribers.UnitTests\bin\%buildconfig%\%buildfrx%\ServiceStack.Webhooks.Subscribers.UnitTests.dll" "C:\projects\servicestack-webhooks\src\Webhooks.UnitTests\bin\%buildconfig%\%buildfrx%\ServiceStack.Webhooks.UnitTests.dll" --result=myresults.xml;format=AppVeyor


    nunit3-console "C:\projects\servicestack-webhooks\src\Webhooks.IntTests\bin\%buildconfig%\%buildfrx%\ServiceStack.Webhooks.IntTests.dll" "C:\projects\servicestack-webhooks\src\Webhooks.OrmLite.IntTests\bin\%buildconfig%\%buildfrx%\ServiceStack.Webhooks.OrmLite.IntTests.dll" --inprocess --result=myresults.xml;format=AppVeyor
artifacts:
- path: '**\ServiceStack.Webhooks.*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: IOhQyRtNmDLFQCHDAlihYB9gVTqimDBKBPEcjSvJEwRF7Hlkxncz3a+FEWsKCSJv
  skip_symbols: true
  on:
    branch: master