//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceStack.Webhooks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceStack.Webhooks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription Config is invalid.
        /// </summary>
        public static string CreateSubscriptionValidator_InvalidConfig {
            get {
                return ResourceManager.GetString("CreateSubscriptionValidator_InvalidConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription Events are invalid.
        /// </summary>
        public static string CreateSubscriptionValidator_InvalidEvents {
            get {
                return ResourceManager.GetString("CreateSubscriptionValidator_InvalidEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription Name is invalid.
        /// </summary>
        public static string CreateSubscriptionValidator_InvalidName {
            get {
                return ResourceManager.GetString("CreateSubscriptionValidator_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription Id is invalid.
        /// </summary>
        public static string DeleteSubscriptionValidator_InvalidId {
            get {
                return ResourceManager.GetString("DeleteSubscriptionValidator_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID is not a valid entity identifier.
        /// </summary>
        public static string EntityIdValidator_ErrorMessage {
            get {
                return ResourceManager.GetString("EntityIdValidator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription Id is invalid.
        /// </summary>
        public static string GetSubscriptionValidator_InvalidId {
            get {
                return ResourceManager.GetString("GetSubscriptionValidator_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EventName is invalid.
        /// </summary>
        public static string SearchSubscriptionsValidator_InvalidEventName {
            get {
                return ResourceManager.GetString("SearchSubscriptionsValidator_InvalidEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription Secret is invalid.
        /// </summary>
        public static string SubscriptionConfigValidator_InvalidSecret {
            get {
                return ResourceManager.GetString("SubscriptionConfigValidator_InvalidSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription URL is invalid.
        /// </summary>
        public static string SubscriptionConfigValidator_InvalidUrl {
            get {
                return ResourceManager.GetString("SubscriptionConfigValidator_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription ContentType is not supported.
        /// </summary>
        public static string SubscriptionConfigValidator_UnsupportedContentType {
            get {
                return ResourceManager.GetString("SubscriptionConfigValidator_UnsupportedContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id is invalid.
        /// </summary>
        public static string SubscriptionDeliveryResultValidator_InvalidId {
            get {
                return ResourceManager.GetString("SubscriptionDeliveryResultValidator_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription Id is invalid.
        /// </summary>
        public static string SubscriptionDeliveryResultValidator_InvalidSubscriptionId {
            get {
                return ResourceManager.GetString("SubscriptionDeliveryResultValidator_InvalidSubscriptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription Event contains an empty name.
        /// </summary>
        public static string SubscriptionEventsValidator_EmptyName {
            get {
                return ResourceManager.GetString("SubscriptionEventsValidator_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription Event contains an invalid name.
        /// </summary>
        public static string SubscriptionEventsValidator_InvalidName {
            get {
                return ResourceManager.GetString("SubscriptionEventsValidator_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription Event contains no names.
        /// </summary>
        public static string SubscriptionEventsValidator_NoName {
            get {
                return ResourceManager.GetString("SubscriptionEventsValidator_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription for event {0} already exists.
        /// </summary>
        public static string SubscriptionService_DuplicateRegistration {
            get {
                return ResourceManager.GetString("SubscriptionService_DuplicateRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription Id is invalid.
        /// </summary>
        public static string UpdateSubscriptionValidator_InvalidId {
            get {
                return ResourceManager.GetString("UpdateSubscriptionValidator_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL is not valid.
        /// </summary>
        public static string UrlValidator_ErrorMessage {
            get {
                return ResourceManager.GetString("UrlValidator_ErrorMessage", resourceCulture);
            }
        }
    }
}
